package online.theowlery.types.enums;

public enum GuildPermissions {
    // General Server / Channel Permissions
    MANAGE_CHANNEL,
    MANAGE_SERVER,
    VIEW_AUDIT_LOGS,
    VIEW_CHANNEL,
    VIEW_GUILD_INSIGHTS,
    MANAGE_ROLES,
    MANAGE_PERMISSIONS,
    MANAGE_WEBHOOKS,
    MANAGE_GUILD_EXPRESSIONS,
    MANAGE_EVENTS,
    USE_EMBEDDED_ACTIVITIES,
    VIEW_CREATOR_MONETIZATION_ANALYTICS,
    CREATE_GUILD_EXPRESSIONS,
    CREATE_SCHEDULED_EVENTS,

    // Membership Permissions
    CREATE_INSTANT_INVITE,
    KICK_MEMBERS,
    BAN_MEMBERS,
    NICKNAME_CHANGE,
    NICKNAME_MANAGE,
    MODERATE_MEMBERS,

    // Text Permissions
    MESSAGE_ADD_REACTION,
    MESSAGE_SEND,
    MESSAGE_TTS,
    MESSAGE_MANAGE,
    MESSAGE_EMBED_LINKS,
    MESSAGE_ATTACH_FILES,
    MESSAGE_HISTORY,
    MESSAGE_MENTION_EVERYONE,
    MESSAGE_EXT_EMOJI,
    USE_APPLICATION_COMMANDS,
    MESSAGE_EXT_STICKER,
    MESSAGE_ATTACH_VOICE_MESSAGE,
    MESSAGE_SEND_POLLS,
    USE_EXTERNAL_APPLICATIONS,
    PIN_MESSAGES,
    BYPASS_SLOWMODE,

    // Thread Permissions
    MANAGE_THREADS,
    CREATE_PUBLIC_THREADS,
    CREATE_PRIVATE_THREADS,
    MESSAGE_SEND_IN_THREADS,

    // Voice Permissions
    PRIORITY_SPEAKER,
    VOICE_STREAM,
    VOICE_CONNECT,
    VOICE_SPEAK,
    VOICE_MUTE_OTHERS,
    VOICE_DEAF_OTHERS,
    VOICE_MOVE_OTHERS,
    VOICE_USE_VAD,
    VOICE_USE_SOUNDBOARD,
    VOICE_USE_EXTERNAL_SOUNDS,
    VOICE_SET_STATUS,

    // Stage Channel Permissions
    REQUEST_TO_SPEAK,

    // Advanced Permissions
    ADMINISTRATOR,

    UNKNOWN;
}
